"""
Axiom — Jupyter Notebook (.ipynb) Report Generator.

Builds a self-contained notebook from a completed run: the report narrative as
markdown cells, the generated charts embedded as images, the SHAP table, and
runnable code cells to load the trained champion model and score new data. The
notebook is plain nbformat-v4 JSON, so this needs no extra dependencies.
"""

from __future__ import annotations

import json
import re
from typing import Any, Optional


def _md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}


def _code(source: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": source}


def _split_markdown(md: str) -> list[str]:
    """Split a markdown report into cells at H2 (``## ``) boundaries."""
    chunks: list[str] = []
    cur: list[str] = []
    for line in md.splitlines():
        if line.startswith("## ") and cur:
            chunks.append("\n".join(cur).strip())
            cur = [line]
        else:
            cur.append(line)
    if cur:
        chunks.append("\n".join(cur).strip())
    return [c for c in chunks if c]


def _fmt(v: Any) -> str:
    if isinstance(v, float):
        return f"{v:.4f}"
    return "—" if v is None else str(v)


def _summary_markdown(result: dict) -> str:
    """Fallback narrative if no markdown report is available."""
    ds = result.get("dataset") or {}
    rows = [
        f"- **Problem type:** {result.get('problem_type', '—')}",
        f"- **Target:** `{result.get('target_column', '—')}`",
        f"- **Champion model:** **{result.get('best_model', '—')}**",
        f"- **{(result.get('best_metric_name') or 'score').upper()}:** "
        f"{_fmt(result.get('best_metric_value'))}",
        f"- **Rows × columns:** {ds.get('rows', '—')} × {ds.get('columns', '—')}",
    ]
    return "## Executive Summary\n\n" + "\n".join(rows)


def _leaderboard_markdown(result: dict) -> Optional[str]:
    models = [m for m in (result.get("models") or []) if m.get("status") == "trained"]
    if not models:
        return None
    models.sort(key=lambda m: (list((m.get("metrics") or {}).values())[0] if m.get("metrics") else 0), reverse=True)
    lines = ["## Model Leaderboard", "", "| Rank | Model | Metrics | Best |", "|---|---|---|---|"]
    for i, m in enumerate(models, 1):
        metrics = " · ".join(f"{k}={_fmt(v)}" for k, v in list((m.get("metrics") or {}).items())[:3])
        lines.append(f"| {i} | {m.get('name')} | {metrics} | {'★' if m.get('is_best') else ''} |")
    return "\n".join(lines)


def _use_model_code(run_id: str, result: dict) -> str:
    feats = (result.get("features") or {}).get("selected") or []
    target = result.get("target_column") or "target"
    feat_repr = "[\n    " + ",\n    ".join(repr(f) for f in feats) + ",\n]" if feats else "[...]"
    return (
        "# Load the champion model Axiom trained for this run and score new data.\n"
        "import glob, joblib, pandas as pd\n\n"
        f'RUN_ID = "{run_id}"\n'
        "# Axiom saves every model under the run\'s artifacts dir; the champion is\n"
        f"# {result.get('best_model', 'the best model')!r}. Pick its .joblib file:\n"
        'model_files = glob.glob(f"artifacts/{RUN_ID}/models/*.joblib")\n'
        "print(\"available model files:\", model_files)\n"
        'model_path = next((p for p in model_files if "_calibrated" in p or "_tuned" in p), model_files[0])\n'
        "model = joblib.load(model_path)\n\n"
        "# Features the model expects (after Axiom\'s preprocessing + feature engineering).\n"
        f"FEATURES = {feat_repr}\n\n"
        "# Decision threshold: see the F1-optimal threshold in the Executive Summary above\n"
        "# (Axiom tunes it instead of using the naive 0.5 for imbalanced targets).\n"
        "THRESHOLD = 0.5  # <-- replace with the threshold from the report\n\n"
        '# new_data = pd.read_csv("your_new_data.csv")\n'
        "# proba = model.predict_proba(new_data[FEATURES])[:, 1]\n"
        "# predictions = (proba >= THRESHOLD).astype(int)\n"
    )


def _eda_code(result: dict) -> str:
    target = result.get("target_column") or "target"
    return (
        "# Load the original dataset to explore it yourself.\n"
        "import pandas as pd\n\n"
        'df = pd.read_csv("your_dataset.csv")   # <-- the file you uploaded\n'
        "print(df.shape)\n"
        "df.head()\n"
    )


def build_notebook(
    run_info: dict,
    result: dict,
    shap_data: Optional[dict] = None,
    markdown_report: Optional[str] = None,
    visualizations: Optional[list[dict]] = None,
) -> bytes:
    """Render a completed run as a .ipynb notebook and return its bytes."""
    run_id = run_info.get("run_id") or result.get("run_id") or "run"
    cells: list[dict] = []

    cells.append(_md(
        f"# Axiom Pipeline Report\n\n"
        f"**Run:** `{run_id}`  \n"
        f"**Mode:** {run_info.get('mode', 'free')}  \n"
        f"_Generated by Axiom — Autonomous Data Scientist. This notebook documents the "
        f"run and lets you load the trained model; the full multi-stage pipeline "
        f"(leakage detection, calibration, etc.) runs inside Axiom._"
    ))

    # Narrative: prefer the rich markdown report, split into per-section cells.
    if markdown_report:
        for chunk in _split_markdown(markdown_report):
            cells.append(_md(chunk))
    else:
        cells.append(_md(_summary_markdown(result)))
        lb = _leaderboard_markdown(result)
        if lb:
            cells.append(_md(lb))

    # Embed the generated charts as images (Jupyter renders data-URI images).
    viz = [v for v in (visualizations or []) if v.get("base64_png")]
    if viz:
        cells.append(_md("## Visualizations"))
        for v in viz:
            cells.append(_md(
                f"**{v.get('name', 'Chart')}** — {v.get('description', '')}\n\n"
                f"![{v.get('name', 'chart')}](data:image/png;base64,{v['base64_png']})"
            ))

    # Runnable code: use the trained model + explore the data.
    cells.append(_md("## Use the trained model"))
    cells.append(_code(_use_model_code(run_id, result)))
    cells.append(_md("## Explore the dataset"))
    cells.append(_code(_eda_code(result)))

    return _wrap(cells, run_id)


def _wrap(cells: list[dict], run_id: str) -> bytes:
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
            "axiom": {"run_id": run_id},
        },
        "nbformat": 4,
        # minor 4 (not 5) so cells don't require an ``id`` field — keeps the
        # notebook strictly valid without us generating per-cell ids.
        "nbformat_minor": 4,
    }
    return json.dumps(notebook, indent=1).encode("utf-8")


# ── True reproduction notebook ───────────────────────────────────────────────

# (agent_name, section title, what it does) in execution order.
_AGENT_STEPS = [
    ("data_collection", "Data Collection",
     "Load & profile the dataset, detect the problem type, and flag target leakage."),
    ("preprocessing", "Preprocessing",
     "Drop duplicates, impute missing values (and add `<col>__was_missing` indicator "
     "features), handle outliers, and fix dtypes."),
    ("feature_engineering", "Feature Engineering",
     "Encode categoricals (one-hot / frequency), extract datetime parts, scale, drop "
     "low-variance / correlated / **leaky** columns, and select the top features by "
     "mutual information."),
    ("data_splitting", "Data Splitting",
     "Stratified train / validation / test split."),
    ("model_training", "Model Training",
     "Train the model zoo, build a soft-voting ensemble, pick the champion by a "
     "composite score, calibrate its probabilities, and tune the decision threshold."),
    ("error_detection", "Error Detection",
     "Audit for overfitting, leakage, and class imbalance."),
    ("improvement", "Improvement",
     "Optionally tune the champion's hyperparameters (kept only if it beats the champion)."),
    ("finalization", "Finalization",
     "SHAP explanations, the markdown report, and saved artifacts."),
]

_INSPECT = {
    "data_collection": "print('problem type :', state.problem_type)\n"
                       "print('leakage flags :', state.data_quality_flags.get('potential_leakage'))",
    "preprocessing": "print(state.preprocessing_summary)",
    "feature_engineering": "print('selected features:', state.selected_features)",
    "model_training": (
        "for m in sorted(state.model_results, key=lambda r: (r.metrics or {}).get(state.best_metric_name, 0), reverse=True):\n"
        "    star = '*' if m.is_best else ' '\n"
        "    print(f\"{star} {m.model_name:32s} {m.metrics}\")\n"
        "print('\\nCHAMPION:', state.best_model_name, '|', state.best_metric_name, '=', state.best_metric_value,\n"
        "      '| threshold =', state.best_threshold)"
    ),
}


def build_reproduction_notebook(
    run_info: dict,
    result: dict,
    data_path: Optional[str],
    target: Optional[str],
) -> bytes:
    """A standalone notebook that re-runs Axiom's *actual* pipeline, agent by agent.

    Because it calls the real agent code with a fixed seed, running it on the same
    dataset reproduces the same champion and honest score — including the
    automatic leakage handling — rather than a hand-written approximation that
    could drift from the pipeline.
    """
    run_id = run_info.get("run_id") or "run"
    cells: list[dict] = []

    best = result.get("best_model") or "the champion"
    metric = result.get("best_metric_name") or "score"
    metric_val = _fmt(result.get("best_metric_value"))

    cells.append(_md(
        f"# Reproduce: Axiom run `{run_id}`\n\n"
        f"This notebook **re-runs Axiom's exact pipeline** on your dataset, one agent at "
        f"a time, so you can reproduce and inspect every step. It calls the real agent "
        f"code (not a re-implementation), with a fixed random seed — so it reproduces "
        f"the same champion (**{best}**, {metric.upper()} ≈ {metric_val}) and the same "
        f"automatic leakage handling.\n\n"
        f"> **Run this from the Axiom project root** (so `core` and `agents` import). "
        f"Set `DATA_PATH` to the dataset you uploaded."
    ))

    safe_path = (data_path or "data/uploads/your_dataset.csv").replace("\\", "/")
    tgt = repr(target) if target else "None  # set your target column, or None for clustering"
    cells.append(_code(
        "import sys, os\n"
        "# Run from the Axiom project root so these imports resolve:\n"
        "from core.config import load_settings\n"
        "from core.state import PipelineState\n"
        "from core.agent_runner import run_single_agent\n"
        "from core.utils import get_timestamp\n\n"
        f'DATA_PATH = r"{safe_path}"\n'
        f"TARGET    = {tgt}\n\n"
        "settings = load_settings()\n"
        "state = PipelineState(\n"
        '    run_id="reproduction",\n'
        "    raw_data_path=DATA_PATH,\n"
        "    target_column=TARGET,\n"
        "    max_retries=settings.pipeline.max_retries,\n"
        "    started_at=get_timestamp(),\n"
        ")\n"
        "print('Reproducing on', DATA_PATH, '| target =', TARGET)"
    ))

    for i, (agent, title, desc) in enumerate(_AGENT_STEPS, 1):
        cells.append(_md(f"## {i}. {title}\n\n{desc}"))
        code = (
            f'out = run_single_agent("{agent}", state, settings)\n'
            f"print('{agent}:', out.status, f'({{out.duration_seconds:.1f}}s)' if out.duration_seconds else '')\n"
        )
        if agent in _INSPECT:
            code += _INSPECT[agent]
        cells.append(_code(code))

    cells.append(_md(
        "## Result\n\n"
        "The champion and honest metrics below should match the report. Note that any "
        "columns that near-perfectly predict the target (data leakage) were detected and "
        "dropped automatically — which is why the honest score is realistic rather than "
        "the inflated ~99% a naive model that keeps them would report."
    ))
    cells.append(_code(
        "print('Champion model :', state.best_model_name)\n"
        "print('Honest metric  :', state.best_metric_name, '=', state.best_metric_value)\n"
        "print('Test metrics   :', getattr(state, 'test_metrics', None))\n"
        "print('Dropped leakage:', state.data_quality_flags.get('potential_leakage'))"
    ))

    return _wrap(cells, run_id)
